- hosts: localhost
  become: true
  tasks:
  

  
  ### Add APT Repos
  # Kind of a chicken/egg issue with needing
  # ansible-pull to run this script.
  - name: Add Repositories
    apt_repository: repo={{item}} update_cache=yes
    with_items:
      - ppa:ansible/ansible
      - ppa:ubuntubudgie/backports
      - ppa:seafile/seafile-client
    state: present

  ### Initial Update
  - name: Updating Base System
    apt:
      upgrade: yes
      update_cache: yes

  ### Install APT Packages
  - name: Install APT Packages
    apt: name={{item}}state=present update_cache=yes
    with_items:
      - git
      - ncdu
      - tmux
      - openssh-server
      - fish
      - ubuntu-restricted-extras
      - seafile-gui

  ### Remove APT Packages
  - name: Remove APT Packages
    apt: name={{item}}
    with_items:
      - chromium*
      - geary
      - libreoffice*
    state: absent

  ### Install Snap Packages
  - name: Install Snap Packages
    command: snap install {{item}}
    with_items:
      - firefox
      - qownnotes
      - hiri
      - irccloud-desktop
      - hugo
      - libreoffice
      - remmina
      - spotify
      - lxd
      - telegram-desktop

  ### Install Classic Snap Packages
  - name: Install Classic Snap Packages
    command: snap install {{item}} --classic
    with_items:
      - vscode
      - go
      - restic
      - snapcraft

    ### Add my user
  - name: Add Dustin user
    user:
      name: dustin
      comment: Dustin Krysak
      # shell: /usr/bin/fish
      shell: /bin/bash
      groups: sudo, adm, cdrom, dip, plugdev, lpadmin, sambashare
      append: yes
      
  ### Add my github pub key to the server
  - name: Install SSH Pub keys
    authorized_key: user=dustin key=https://github.com/{{item}}.keys
    with_items:
      - bashfulrobot