- hosts: localhost
  become: true

  vars:
    myusername: dustin
    myhome: /home/dustin
    # Used in dotfiles.yml
    # Access vars with:
    # {{ cfg[fish] }}
    cfg:
      fish:
        - config.fish
        - functions/battery.fish
        - functions/do-update.fish
        - functions/get-octals.fish
        - functions/img-up.fish
        - functions/ntfy-send.fish
        - functions/sucode.fish
  pre_tasks:
    - name: Update Repositories
      apt: update_cache=yes
      changed_when: false
  tasks:
    - include: tasks/repos.yml
    - include: tasks/update-system.yml
    - include: tasks/apt.yml
    - include: tasks/snap.yml
    - include: tasks/pip.yml
    - include: tasks/sysctl.yml
    - include: tasks/users.yml
    - include: tasks/sudoers.yml
    - include: tasks/cron.yml
    - include: tasks/dconf.yml
    - include: tasks/services.yml
    - include: tasks/ufw.yml
    - include: tasks/timezone.yml
    - include: tasks/nsswitch.yml
    - include: tasks/dotfiles.yml