- hosts: localhost
  become: true
  tasks:
  
  # Install APT Packages
  - name: Install APT Packages
    apt: name={{item}}
    with_items:
      - git
      - ncdu
      - tmux
      - openssh-server

  # Install Snap Packages
  - name: Install Snap Packages
    command: snap install {{item}}
    with_items:
      - firefox

  # Install Classic Snap Packages
  - name: Install Classic Snap Packages
    command: snap install {{item}} --classic
    with_items:
      - vscode