- hosts: localhost
  become: true
  tasks:
  

  
  ### Add APT Repos
  # Kind of a chicken/egg issue with needing
  # ansible-pull to run this script.
  - apt_repository:
      repo: ppa:ansible/ansible
      state: present

  ### Install APT Packages
  - name: Install APT Packages
    apt: name={{item}}
    with_items:
      - git
      - ncdu
      - tmux
      - openssh-server
      - fish

  ### Remove APT Packages
  - name: Remove APT Packages
    apt: name={{item}}
    with_items:
      - chromium*
    state: absent

  ### Install Snap Packages
  - name: Install Snap Packages
    command: snap install {{item}}
    with_items:
      - firefox
      - qownnotes

  ### Install Classic Snap Packages
  - name: Install Classic Snap Packages
    command: snap install {{item}} --classic
    with_items:
      - vscode

    ### Add my user
  - name: Add Dustin user
    user:
      name: dustin
      comment: Dustin Krysak
      # shell: /usr/bin/fish
      shell: /bin/bash
      groups: sudo, adm, cdrom, dip, plugdev, lpadmin, sambashare
      append: yes
      
  ### Add my github pub key to the server
  - name: Install SSH Pub keys
    authorized_key: user=dustin key=https://github.com/{{item}}.keys
    with_items:
      - bashfulrobot