- name: Remove APT Packages
  apt:
    name:
      '[object Object]': null
    state: absent
  vars:
    rempackages:
      - chromium-*
      - geary
      - libreoffice-*
      - plank
      - docker
      - docker-engine
      - docker.io
- name: Autoremove and Purge APT Packages
  apt:
    autoremove: yes
    purge: yes
- name: Install APT Packages
  apt:
    name:
      '[object Object]': null
  vars:
    packages:
      - git
      - xclip
      - ncdu
      - tmux
      - openssh-server
      - fish
      - ubuntu-restricted-extras
      - seafile-gui
      - debconf-utils
      - lftp
      - htop
      - deluge-gtk
      - network-manager-vpnc
      - network-manager-vpnc-gnome
      - budgie-*-applet
      - gnome-mpv
      - calibre
      - whois
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - docker-ce
      - cowsay
- name: Remove APT Packages
  apt:
    name:
      '[object Object]': null
    state: absent
  vars:
    rempackages:
      - chromium-*
      - geary
      - libreoffice-*
      - plank
- name: Autoremove and Purge APT Packages
  apt:
    autoremove: yes
    purge: yes
