- name: Remove APT Packages
  apt:
    name: '{{ rempackages }}'
    state: absent
  vars:
    rempackages:
      - geary
      - fish
      - libreoffice-*
      - docker
      - docker-engine
      - docker.io
      - ibus
- name: Autoremove and Purge APT Packages
  apt:
    autoremove: yes
    purge: yes
- name: Install APT Packages
  apt:
    name: '{{ packages }}'
  vars:
    packages:
      - git
      - neovim
      - hstr
      - xclip
      - ncdu
      - tmux
      - openssh-server
      - ubuntu-restricted-extras
      - debconf-utils
      - lftp
      - htop
      - deluge-gtk
      - budgie-*-applet
      - gnome-mpv
      - calibre
      - whois
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - docker-ce
      - cowsay
      - python-pip
      - meld
      - figlet
      - typora
      - nomacs
      - uncrustify
      - snapd-xdg-open
      - rtv
- name: Autoremove and Purge APT Packages
  apt:
    autoremove: yes
    purge: yes
