### Install APT Packages
- name: Install APT Packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - git
    - xclip
    - ncdu
    - tmux
    - openssh-server
    - fish
    - ubuntu-restricted-extras
    - seafile-gui
    - debconf-utils
    - lftp
    - htop
    - deluge-gtk
    - network-manager-vpnc
    - network-manager-vpnc-gnome
<<<<<<< HEAD
=======
    - budgie-*-applet
>>>>>>> 9646b35993f3a00397d4d8993422d72383d82f53

### Remove APT Packages
- name: Remove APT Packages
  apt:
    name: "{{ rempackages }}"
    state: absent
  vars:
    rempackages:
      - chromium-*
      - geary
      - libreoffice-*
      - plank

### Clean out unwanted apt stuff
- name: Autoremove and Purge APT Packages
  apt:
    autoremove: yes
    purge: yes