# Needed for dconf
- name: Install python-psutil package
  apt:
    name: python-psutil
# Set default Wallpaper
- name: Copy Default Wallpaper
  copy:
    src: files/Rubiks-HDPI.jpg
    dest: "{{ myhome }}Pictures/wallpaper.jpg"
    owner: "{{ myusername }}"
    group: "{{ myusername }}"
    mode: 775
# Set Wallpaper
- name: Set Default Wallpaper
  dconf:
    key: "/org/gnome/desktop/background/picture-uri"
    value: "'file://{{ myhome }}Picures/wallpaper.jpg'"
# Set Lockscreen
- name: Set Default Lockscreen Wallpaper
  dconf:
    key: "/org/gnome/desktop/screensaver/picture-uri"
    value: "'file://{{ myhome }}Picures/wallpaper.jpg'"
