### Needed for dconf
- name: Install psutils python-psutil package
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - python-psutil
    - psutils
### Set default Wallpaper
- name: Copy Default Wallpaper
  copy:
    src: files/Rubiks-HDPI.jpg
    dest: "/home/{{ myusername }}/Pictures/wallpaper.jpg"
### Set Wallpaper permission
- name: Set Wallpaper File Permissions
  file:
    path: "/home/{{ myusername }}/Pictures/wallpaper.jpg"
    owner: "dustin"
    group: "dustin"
    mode: 0775

### Set Wallpaper
- name: Set Default Wallpaper
  dconf:
    user: 'dustin'
    key: '/org/gnome/desktop/background/picture-uri'
    value: "'file:///home/dustin/Pictures/wallpaper.jpg'"

### Set Lockscreen
- name: Set Default Lockscreen Wallpaper
  dconf:
    user: 'dustin'
    key: '/org/gnome/desktop/screensaver/picture-uri'
    value: "'file:///home/dustin/Pictures/wallpaper.jpg'"