- name: Install psutils python-psutil package
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - python-psutil
      - psutils
- name: Copy Default Wallpaper
  copy:
    # src: files/Rubiks-HDPI.jpg
    src: files/Btf.jpg
    dest: "/home/{{ myusername }}/Pictures/wallpaper.jpg"
- name: Set Wallpaper File Permissions
  file:
    path: "/home/{{ myusername }}/Pictures/wallpaper.jpg"
    owner: "{{ myusername }}"
    group: "{{ myusername }}"
    mode: 0775
- name: Set Default Wallpaper
  become: true
  become_user: "{{ myusername }}"
  dconf:
    key: "/org/gnome/desktop/background/picture-uri"
    value: "'file:///home/{{ myusername }}/Pictures/wallpaper.jpg'"
    state: present
- name: Set Default Lockscreen Wallpaper
  become: true
  become_user: "{{ myusername }}"
  dconf:
    key: "/org/gnome/desktop/screensaver/picture-uri"
    value: "'file:///home/{{ myusername }}/Pictures/wallpaper.jpg'"
    state: present
- name: Enable Nightlight
  become: true
  become_user: "{{ myusername }}"
  dconf:
    key: "/org/gnome/settings-daemon/plugins/color/night-light-enabled"
    value: "true"
    state: present
- name: Changing Terminal Keyboard Shortcut
  become: true
  become_user: "{{ myusername }}"
  dconf:
    key: "/org/gnome/settings-daemon/plugins/media-keys/terminal"
    value: "'<Super>Return'"
    state: present
- name: Changing Close Application Keyboard Shortcut
  become: true
  become_user: "{{ myusername }}"
  dconf:
    key: "/org/gnome/desktop/wm/keybindings/close"
    value: "['<Super>q']"
    state: present
- name: Changing Run Application Keyboard Shortcut
  become: true
  become_user: "{{ myusername }}"
  dconf:
    key: "/org/gnome/desktop/wm/keybindings/panel-run-dialog"
    value: "['<Super>space']"
    state: present
- name: Changing Run Application Keyboard Shortcut
  become: true
  become_user: "{{ myusername }}"
  dconf:
    key: "/org/gnome/desktop/peripherals/touchpad/natural-scroll"
    value: "false"
    state: present
- name: Set Theme to Dark
  become: true
  become_user: "{{ myusername }}"
  dconf:
    key: "/com/solus-project/budgie-panel/dark-theme"
    value: "true"
    state: present
- name: Add Trash Icon to the Desktop
  become: true
  become_user: "{{ myusername }}"
  dconf:
    key: "/org/gnome/nautilus/desktop/trash-icon-visible"
    value: "false"
    state: present
- name: Add Mounted Volume Icon to the Desktop
  become: true
  become_user: "{{ myusername }}"
  dconf:
    key: "/org/gnome/nautilus/desktop/volumes-visible"
    value: "false"
    state: present
- name: Add Home Folder Icon to the Desktop
  become: true
  become_user: "{{ myusername }}"
  dconf:
    key: "/org/gnome/nautilus/desktop/home-icon-visible"
    value: "false"
    state: present
- name: Add Network Icons to the Desktop
  become: true
  become_user: "{{ myusername }}"
  dconf:
    key: "/org/gnome/nautilus/desktop/network-icon-visible"
    value: "false"
    state: present
- name: Changing IBUS Emjoi Keyboard Shortcut
  become: true
  become_user: "{{ myusername }}"
  dconf:
    key: "/desktop/ibus/panel/emoji/hotkey"
    value: "['<Control><Alt><Shift>e']"
    state: present
- name: Set Icon Theme
  become: true
  become_user: "{{ myusername }}"
  dconf:
    key: "/org/gnome/desktop/interface/icon-theme"
    value: "'breeze-dark'"
    state: present
- name: Set gtk-im-module
  become: true
  become_user: "{{ myusername }}"
  dconf:
    key: "/org/gnome/desktop/interface/gtk-im-module"
    value: "'gtk-im-context-simple'"
    state: present
- name: Set Cursor Theme
  become: true
  become_user: "{{ myusername }}"
  dconf:
    key: "/org/gnome/desktop/interface/cursor-theme"
    value: "'Breeze_Snow'"
    state: present
- name: Set System Theme
  become: true
  become_user: "{{ myusername }}"
  dconf:
    key: "/org/gnome/desktop/interface/gtk-theme"
    # Needed extra quotes due to unlnown key error
    value: "'Breeze-Dark'"
    state: present
- name: Set Screen Idle Time
  become: true
  become_user: "{{ myusername }}"
  dconf:
    key: "/org/gnome/desktop/session/idle-delay"
    value: "uint32 600"
    state: present
- name: Set Remove Super Space Defaults
  become: true
  become_user: "{{ myusername }}"
  dconf:
    key: "/org/gnome/desktop/wm/keybindings/switch-input-source-backward"
    value: "['<Primary><Alt><Super>space']"
    state: present
- name: Set Remove Super Space Defaults
  become: true
  become_user: "{{ myusername }}"
  dconf:
    key: "/org/gnome/desktop/wm/keybindings/switch-input-source"
    value: "['<Primary><Shift><Alt><Super>space']"
    state: present
