- name: Copy Fish Cfg Files
  copy:
    # {{ cfg[fish] }} - comes from vars/main.yml
    src: "files/fish/{{ cfg[fish] }}"
    dest: "/home/{{ myusername }}/.config/fish/{{ cfg[fish] }}"

- name: Set Fish Cfg File Permissions
  file:
    path: "/home/{{ myusername }}/.config/fish/{{ cfg[fish] }}"
    owner: "{{ myusername }}"
    group: "{{ myusername }}"
    mode: 0664