- name: Fixing .local Name Resolution - Ubuntu
  lineinfile:
    path: /etc/nsswitch.conf
    regex: '^hosts:(.*)files mdns.*'
    state: present
    line: 'hosts:          files dns mdns4_minimal [NOTFOUND=return] myhostname'
  become: true
