### Install Snap Packages
- name: Install Snap Packages
  command: snap install "{{ item }}"
  with_items:
    - firefox
    - qownnotes
    - hiri
    - irccloud-desktop
    - hugo
    - libreoffice
    - remmina
    - spotify
    - lxd
    - telegram-desktop
    - opera
    - simplescreenrecorder

### Install Classic Snap Packages
- name: Install Classic Snap Packages
  command: snap install "{{ item }}" --classic
  with_items:
    - vscode
    - go
    - restic
    - snapcraft
    - hiri

### Remmina Snap CFG
- name: Remmina Snap CFG
  command: snap connect remmina:"{{ item }}" :"{{ item }}"
  with_items:
    - avahi-observe
    - cups-control
    - mount-observe
    - password-manager-service
