- name: Install Snap Packages
  command: 'snap install "{{ item }}"'
  with_items:
    - firefox
    - qownnotes
    - irccloud-desktop
    - hugo
    - libreoffice
    - remmina
    - spotify
    - lxd
    - telegram-desktop
    - simplescreenrecorder
    - bitwarden
    - bw
    - discord
    - gravit-designer
    - serve
    - icdiff
- name: Install Classic Snap Packages
  command: 'snap install "{{ item }}" --classic'
  with_items:
    - vscode
    - go
    - restic
    - snapcraft
    - slack
- name: Remmina Snap CFG
  command: 'snap connect remmina:"{{ item }}" :"{{ item }}"'
  with_items:
    - avahi-observe
    - cups-control
    - mount-observe
    - password-manager-service