### Create sudoers file for Ansible
- name: Add ansible-pull sudoer file
  file:
    path: /etc/sudoers.d/ansible_pull
    state: touch
    owner: root
    group: root
    mode: 0440

### Add ansible-pull and Validate the sudoers file before saving
- name: Allow ansible-pull with no password
  lineinfile:
    path: /etc/sudoers.d/ansible_pull
    line: 'dustin ALL=(ALL) NOPASSWD: /usr/bin/ansible-pull'
    # state: present
    validate: '/usr/sbin/visudo -cf %s'