- name: Remove APT Packages
  apt:
    name: "{{ rempackages }}"
    state: absent
  vars:
    rempackages:
      - geary
      - libreoffice-*
      - docker
      - docker-engine
      - docker.io
      - ibus
      - plank
- name: Autoremove and Purge APT Packages
  apt:
    autoremove: yes
    purge: yes
- name: Install APT Packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - git
      - neovim
      - xclip
      - ncdu
      - tmux
      - openssh-server
      - ubuntu-restricted-extras
      - debconf-utils
      - lftp
      - htop
      - deluge-gtk
      - budgie-*-applet
      - gnome-mpv
      - calibre
      - whois
      - apt-transport-https
      - ca-certificates
      - software-properties-common
      - cowsay
      - python-pip
      - meld
      - figlet
      - nomacs
      - uncrustify
      - snapd-xdg-open
      - rtv
      - breeze-icon-theme
      - breeze-gtk-theme
      - breeze-cursor-theme
      - grub-theme-breeze
      - asciinema
      - flameshot
      - python-psutil
      - psutils
      - libimage-exiftool-perl
      - firefox
      - python3-pip
      - libcurl4
      - curl
      - gnupg-agent
      - font-manager
      - code
      - gnome-calculator

- name: Autoremove and Purge APT Packages
  apt:
    autoremove: yes
    purge: yes
