- name: Add Launchpad PPAs
  apt_repository:
    repo: "{{ item }}"
    update_cache: yes
    state: present
  with_items:
    - ppa:ubuntubudgie/backports
    - ppa:seafile/seafile-client
    - ppa:geary-team/releases

- name: Add Canonical Partners PPA
  apt_repository:
    repo: deb http://archive.canonical.com/ubuntu {{ansible_distribution_release}} partner
    state: present

- name: Add an Apt signing key for Vscode
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: Add Vscode MS PPA
  apt_repository:
    repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
    state: present
