- name: Install Snap Packages
  command: 'snap install "{{ item }}"'
  with_items:
    - yakyak
    - irccloud-desktop
    - hugo
    - libreoffice
    - remmina
    - spotify
    - lxd
    - telegram-desktop
    - simplescreenrecorder
    - bitwarden
    - bw
    - discord
    - mailspring
    #- gravit-designer
    - serve
    - icdiff
    - pocket-casts
    - gnome-twitch
    - gotop
    - mumble
    - docker
    - typora-alanzanattadev
    #- youtube-dl # Needs edge channel
- name: Install Classic Snap Packages
  command: 'snap install "{{ item }}" --classic'
  with_items:
    - go
    - restic
    - snapcraft
    - slack
    - snapdiff
    - aws-cli
- name: Install Node Snap Package
  command: 'snap install node --channel=11/stable --classic'
- name: Remmina Snap CFG
  command: 'snap connect remmina:"{{ item }}" :"{{ item }}"'
  with_items:
    - avahi-observe
    - cups-control
    - mount-observe
    - password-manager-service
